#!/usr/bin/php
<?php


require "cliarg.php";


$arguments = [
  "dir" => ".", 
  "ver" => false, 
  "all" => false, 
  "rec" => 5,
  "ext" => ".*"
];

$expected = [
  'd:' => 'directory',
  'v' => 'verbose',
  'a' => 'all',
  'r:' => 'recursive',
  'h' => 'help',
  'e:' => 'extension'
];

$error = [];

$nb_files = array(0, 0);

$cliarg = new Cliarg($expected, $argv);
$expected = $cliarg->check($error);

if ($expected === ARG_ERROR)
{
  echo "\e[0;31m";
  foreach ($error as $e) {
    echo "Argument '$e' incorrect !" . PHP_EOL;
  }
  echo "\e[0m";
  return ARG_ERROR;
}
else if ($expected === USR_ERROR) return USR_ERROR;
else if ($expected['h'] === true) {
  echo Help();
  return 0;
}

if (isset($expected['d'])) $arguments['dir'] = $expected['d'];
if (isset($expected['r'])) $arguments['rec'] = (int)$expected['r'];
if (isset($expected['e'])) $arguments['ext'] = $expected['e'];
$arguments['ver'] = $expected['v'];
$arguments['all'] = $expected['a'];


$ki = new Ki($arguments);
$ki->Display();


class Ki
{
  private $arg;

  public function __construct(array $arguments)
  {
    $this->arg = $arguments;
  }

  public function Display()
  {
    echo PHP_EOL . "\e[1;34m" . $this->arg['dir'] . PHP_EOL;
    $this->Recursive($this->arg['dir'], 1);
  }

  private function Recursive($path, $lvl)
  {
    if ($lvl > $this->arg['rec']) return;

    $files = [];
    $dirs = [];

    if (is_dir($path)) 
    {
      if (($dir = opendir($path)) !== false)
      {
        while (($file = readdir($dir)) !== false)
        {
          if ($file === '.' || $file === '..') continue;
          if ($this->arg['all'] || substr($file, 0, 1) !== '.')
          {
            $full_file = $path . DIRECTORY_SEPARATOR . $file;
            if (is_dir($full_file)) $dirs[] = $file;
            else if (file_exists($full_file)) 
            {
              if ($this->arg['ext'] == '.*' || preg_match('#\.' . $this->arg['ext'] . '$#', $file))
              $files[] = $file;
            }
          }
        }
      }
      closedir($dir);

      if (isset($files[0])) 
        $this->DisplayFiles($path, $files, $lvl);
      if (isset($dirs[0]))
        $this->DisplayDirs($path, $dirs, $lvl);
    }
  }

  private function DisplayFiles($path, $files, $lvl)
  {
    $first_time = true;
    $margin = $this->GetMargin($lvl, $path, true, true);
    natsort($files);

    foreach ($files as $file)
    {
      $color = $this->GetColor($path, $file);

      if ($this->arg['ver']) {
        $perms = $this->GetPerms($path . DIRECTORY_SEPARATOR . $file);
        $size = $this->GetSize($path . DIRECTORY_SEPARATOR . $file);
        echo $margin . $perms . $size . $color . $file . "\e[0m" . PHP_EOL;
      }
      else {
        echo $margin . $color . $file . "\e[0m" . PHP_EOL;
      }
      if ($first_time) {
        $margin = $this->GetMargin($lvl, $path, true);
        $first_time = false;
      }
    }
  }

  private function DisplayDirs($path, $dirs, $lvl)
  {
    $margin = $this->GetMargin($lvl, $path);
    natsort($dirs);

    foreach ($dirs as $dir)
    {
      $color = "\e[1;34m";

      echo $margin . $color . $dir . DIRECTORY_SEPARATOR . "\e[0m" . PHP_EOL;
      $this->Recursive($path . DIRECTORY_SEPARATOR . $dir, $lvl + 1);
    }
  }

  private function GetMargin($lvl, $path, $isfile = false, $first_file = false)
  {
    $margin = "\e[0;37m";
    $j;
    for ($j = 1; $j < $lvl; $j++) {
      $margin .= '-';
      if ($j + 1 < $lvl) $margin .= "\e[0;36m+\e[0;37m";
    }
    if ($j > 1) $margin .= '>';
    $margin .= ' ';
    if (!$isfile) $margin .= $path . DIRECTORY_SEPARATOR;
    return $margin . "\e[0m";
  }

  private function GetSize($file)
  {
    $size = filesize($file);
    $KB_size = 1024;
    $MB_size = 1048576;
    $GB_size = 1073741824;
    $KB = 0;
    $MB = 0;
    $GB = 0;
    $final_size = "";

    if (($tmp = (int)($size / $GB_size)) >= 1) {
      $GB = $tmp;
      $size -= $tmp * $GB_size; 
    }
    if (($tmp = (int)($size / $MB_size)) >= 1) {
      $MB = $tmp;
      $size -= $tmp * $MB_size;
    }
    if (($tmp = (int)($size / $KB_size)) >= 1) {
      $KB = $tmp;
      $size -= $tmp * $KB_size;
    }
    $tmp = "";

    if ($GB > 0) {
      if ($MB >= 1000) $tmp = ',99';
      else if ($MB >= 100) $tmp = ',' . substr((string)$MB, 0, 2);
      else if ($MB >= 10) $tmp = ',0' . substr((string)$MB, 0, 1);
      $final_size = $GB . $tmp . " GB";
    }
    else if ($MB > 0) {
      if ($KB >= 1000) $tmp = ',99';
      else if ($KB >= 100) $tmp = ',' . substr((string)$KB, 0, 2);
      else if ($KB >= 10) $tmp = ',0' . substr((string)$KB, 0, 1);
      $final_size = $MB . $tmp . " MB";
    }
    else if ($KB > 0) {
      if ($size >= 1000) $tmp = ',99';
      else if ($size >= 100) $tmp = ',' . substr((string)$size, 0, 2);
      else if ($size >= 10) $tmp = ',0' . substr((string)$size, 0, 1);
      $final_size = $KB . $tmp . " KB";
    }
    else
      $final_size = $size . " B";

    return " " . $final_size . " ";
  }

  private function GetPerms($file)
  {
    $perms = fileperms($file);

    if (($perms & 0xC000) == 0xC000)
      $info = 's';
    elseif (($perms & 0xA000) == 0xA000)
      $info = 'l';
    elseif (($perms & 0x8000) == 0x8000)
      $info = '-';
    elseif (($perms & 0x6000) == 0x6000)
      $info = 'b';
    elseif (($perms & 0x4000) == 0x4000)
      $info = 'd';
    elseif (($perms & 0x2000) == 0x2000)
      $info = 'c';
    elseif (($perms & 0x1000) == 0x1000)
      $info = 'p';
    else
      $info = 'u';

    // Root 
    $info .= (($perms & 0x0100) ? 'r' : '-');
    $info .= (($perms & 0x0080) ? 'w' : '-');
    $info .= (($perms & 0x0040) ?
        (($perms & 0x0800) ? 's' : 'x' ) :
        (($perms & 0x0800) ? 'S' : '-'));

    // Groupe
    $info .= (($perms & 0x0020) ? 'r' : '-');
    $info .= (($perms & 0x0010) ? 'w' : '-');
    $info .= (($perms & 0x0008) ?
        (($perms & 0x0400) ? 's' : 'x' ) :
        (($perms & 0x0400) ? 'S' : '-'));

    // Tout le monde
    $info .= (($perms & 0x0004) ? 'r' : '-');
    $info .= (($perms & 0x0002) ? 'w' : '-');
    $info .= (($perms & 0x0001) ?
        (($perms & 0x0200) ? 't' : 'x' ) :
        (($perms & 0x0200) ? 'T' : '-'));
    return $info;
  }

  private function GetColor($path, $file)
  {
    $b = "\e[";

    $b .= is_executable($path . DIRECTORY_SEPARATOR . $file) ? '1;': '0;';

		preg_match("#\.[a-zA-Z3-4]+$#", $file, $ext);

		if (isset($ext[0]))
			$ext = strToLower(substr($ext[0], 1));
		else return $b . '35m';

		switch ($ext) {
		//IMG
			case 'jpg' :
			case 'jpeg':
			case 'bmp' :
			case 'gif' :
			case 'png' :
			case 'tiff':
			case 'tif' : return $b . "33m";
		//SOUND
			case 'mp3' :
			case 'wma' :
			case 'wave':
			case 'riff':
			case 'aiff':
			case 'raw' :
			case 'ogg' : return $b . "37m";
		//VIDEO
			case 'mp4' :
			case 'avi' :
			case 'wmv' :
			case 'mov' :
			case 'flv' :
			case 'mpg' :
			case 'rmvb': return $b . "32m";
		//TEXT
			case 'txt':
			case 'odt':
			case 'xls':
			case 'doc':
			case 'rtf':
			case 'odb':
			case 'odc':
			case 'odf': 
			case 'odg': 
			case 'odp': 
			case 'ods': 
			case 'oxt': 
			case 'mus': 
			case 'gp3': 
			case 'gp4': 
			case 'gp5': 
			case 'gp6': 
			case 'pdf': return $b . "36m";
		//PROGRAMMING
			case 'php'  : 
			case 'bat'  : 
			case 'asm'  : 
			case 'html' : 
			case 'css'  : 
			case 'c'    : 
			case 'cs'   : 
			case 'scss' : 
			case 'sass' : 
			case 'cpp'  : 
			case 'py'   : 
			case 'js'   : 
			case 'json' : 
			case 'xml'  : 
			case 'sql'  : 
			case 'ksh'  : 
			case 'sh'   : 
			case 'pyw'  : 
			case 'rb'   : 
			case 'xhtml': 
			case 'htm'  : 
			case 'vim'  : 
			case 'atom' : 
			case 'h'    : 
			case 'java' : return $b . "31m";
		//
			case 'a'  : 
			case 'o'  : 
			case 'iso': 
      case 'exe': 
      case 'com': 
      case 'elf': return $b . "34m";
		//
			default : return $b . "35m";
		}

  }
}

function Help()
{
  return "\e[7;31m                             Mode d'emploi :                                \e[0m" . PHP_EOL . PHP_EOL
    . "\e[1;31mki \e[0m[\e[1;31m-r\e[0m=\e[0;33m\"recursive\"\e[0m]\e[1;32m?\e[0m"
    . " [\e[1;31m-d\e[0m=\e[0;33m\"directory\"\e[0m]\e[1;32m?\e[0m"
    . " [\e[1;31m-e\e[0m=\e[0;33m\"extension\"\e[0m]\e[1;32m?\e[0m"
    . " [\e[1;31m-a\e[0m]\e[1;32m?\e[0m"
    . " [\e[1;31m-v\e[0m]\e[1;32m?\e[0m"
    . " [\e[1;31m-h\e[0m]\e[1;32m?" . PHP_EOL . PHP_EOL
    . "\e[0;32mArguments : " . PHP_EOL
    . "  \e[0;36m-r / --recursive : \e[0;37mRecursive level \e[0m(\e[1;34minteger\e[0m)" . PHP_EOL
    . "  \e[0;36m-d / --directory : \e[0;37mRoot's directory of the tree \e[0m(\e[1;34mstring\e[0m)" . PHP_EOL
    . "  \e[0;36m-a / --all       : \e[0;37mPrinting all the files and directories \e[0m(\e[1;34mboolean\e[0m)" . PHP_EOL
    . "  \e[0;36m-v / --verbose   : \e[0;37mPrinting files informations \e[0m(\e[1;34mboolean\e[0m)" . PHP_EOL
    . "  \e[0;36m-e / --extension : \e[0;37mPrinting only the files who have the same extension \e[0m(\e[1;34mregex\e[0m)" . PHP_EOL
    . "  \e[0;36m-h / --help      : \e[0;37mPrinting help menu (and quit whitout to print the tree) \e[0m(\e[1;34mboolean\e[0m)" . PHP_EOL . PHP_EOL;
}
